# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Analyse Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: flutter analyze
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      # - name: Initialize bundler
      #   run: bundler init

      # - name: Setup Danger
      #   run: gem install bundler && gem install danger && bundle install

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        
      - name: Caching
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            architecture: x64
      
      - name: Install packages
        run: flutter pub get

      - name: Analyze flutter
        run: flutter analyze > flutter_analyze_report.txt

      - name: Execute Danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: '.github/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
