name: Run unit tests

on:
  pull_request:
    branches: 
      - '**'

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out actions
        uses: actions/checkout@v3

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install packages
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Activate test coverage console
        run: flutter pub global activate test_cov_console
        
      - name: Show code coverage
        run: flutter pub global run test_cov_console > code_coverage_report.txt

      - name: Comment PR
        if: ${{ always() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            code_coverage_report.txt
          allow-repeats: false
