name: Run unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Check out actions
        uses: actions/checkout@v3
      - name: Check out flutter actions
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install packages
        run: flutter pub get
      - name: Run unit tests
        run: flutter test --coverage
      - name: Activate test coverage console
        run: flutter pub global activate test_cov_console
      - name: Show code coverage
        run: flutter pub global run test_cov_console 
