name: Run unit tests

on:
  pull_request:
    branches: 
      - '**'

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out actions
        uses: actions/checkout@v3

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install packages
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Activate test coverage console
        run: flutter pub global activate test_cov_console
        
      - name: go to
        run: mkdir -p output/
        
      - name: Show code coverage
        run: flutter pub global run test_cov_console > output/results.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: output
          
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: results
          
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.txt
#       - name: Comment PR
#         if: ${{ always() }}
#         uses: marocchino/sticky-pull-request-comment@v2
#         with:
#           header: "unit_test"
#           hide_and_recreate: true
#           hide_classify: "OUTDATED"
#           path: code_coverage_report.txt
